name: 'notion-to-markdown-action'
description: ''
author: 'ega4432'
inputs:
  notion_api_key:
    required: true
    description: ''
  notion_database_id:
    required: true
    description: ''
  output:
    required: false
    description: ''
    default: 'output'
runs:
  using: 'node16'
  main: 'dist/index.js'
